### ISSUE TITLE
API return 404

### ISSUE THREAD

**Issue by vachaganbalayan** [crypto-com/crypto-exchange#1]
Simple piece of code, and i always get 404 are you actually live?
```
const WebSocket = require('ws');
const ws = new WebSocket("wss://ws.crypto.com");

ws.on('open', function open() {
    ws.send(`{"event":"req","params":{"channel":"review"}}`);
    // ws.send(`{"event":"sub","params":{"channel":"market_btcusdt_ticker","cb_id":"custom"}}`);
});

ws.on('message', (it) => {
    console.log(`<< : ${it}`)
});
```

output 

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.req.on (/Users/vach/work/jarvis/node_modules/ws/lib/websocket.js:542:5)
    at ClientRequest.emit (events.js:160:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:548:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:599:20)
```

**Comment by mcomc** [comment]
The web socket URL has been revised, thanks for pointing this out
